configfile: "config/config.yaml"

rule all:
    input:
        "results/import.rds",
        "results/getmset.rds",
        "results/getrset.rds"

rule import:
    input:
        dir = "data"
    output:
        rds = "results/import.rds"
    log:
        out = "results/import.out",
        err = "results/import.err"
    message:
        "Importing data..."
    conda:
        "envs/minfi.yaml"
    script:
        "scripts/import.R"

rule getmset:
    input:
        rds = "results/import.rds"
    output:
        rds = "results/getmset.rds"
    log:
        out = "results/getmset.out",
        err = "results/getmset.err"
    message:
        "Converting RGset to MSet"
    conda:
        "envs/environment.yaml"
    script:
        "scripts/getmset.R"

rule getrset:
    input:
        rds = "results/getmset.rds"
    output:
        rds = "results/getrset.rds"
    params:
        what = "both",
        keepCN = True
    log:
        out = "results/getrset.out",
        err = "results/getrset.err"
    message:
        "Converting MSet to RSet"
    conda:
        "envs/environment.yaml"
    script:
        "scripts/getrset.R"
